CREATE DATABASE LetsCar;
GO

USE LetsCar;
GO

CREATE TABLE Pessoa
(
	Id				INT IDENTITY NOT NULL,
	Nome			VARCHAR(100) NOT NULL,
	DataNascimento	DATE NOT NULL,
	CONSTRAINT PK_Pessoa PRIMARY KEY(Id)
)

CREATE TABLE Cliente
(
	Id			INT IDENTITY NOT NULL,
	IdPessoa	INT NOT NULL,
	CONSTRAINT PK_Cliente PRIMARY KEY(Id),
	CONSTRAINT FK_Pessoa
		FOREIGN KEY (IdPessoa)
		REFERENCES Pessoa(Id)
)

CREATE TABLE Marca
(
	Id		INT IDENTITY NOT NULL,
	Nome	VARCHAR(10) NOT NULL,
	CONSTRAINT PK_Marca PRIMARY KEY(Id)
)

CREATE TABLE Modelo
(
	Id		INT IDENTITY NOT NULL,
	Nome	VARCHAR(20) NOT NULL,
	CONSTRAINT PK_Modelo PRIMARY KEY(Id)
)

CREATE TABLE Ano
(
	Id		INT IDENTITY NOT NULL,
	AnoModelo	DATE NOT NULL,
	AnoFabricacao	DATE, /*NULL SE INFORMACAO NAO ESTIVER DISPONIVEL E NAO INTERFERE NO VALOR*/
	CONSTRAINT PK_Ano PRIMARY KEY(Id)
)

CREATE TABLE Cor
(
	Id		INT IDENTITY NOT NULL,
	Nome	VARCHAR(10) NOT NULL,
	CONSTRAINT PK_Cor PRIMARY KEY(Id)
)

CREATE TABLE ModoPagamento
(
	Id			INT IDENTITY NOT NULL,
	Nome		VARCHAR(10) NOT NULL,
	Desconto	DECIMAL(10,2),
	CONSTRAINT PK_ModoPagamento PRIMARY KEY(Id)
)

CREATE TABLE Financeiro
(
	Id				INT IDENTITY NOT NULL,
	Preco			DECIMAL(15,2) NOT NULL,
	IdModoPagamento	INT NOT NULL,
	CONSTRAINT PK_Financeiro PRIMARY KEY(Id),
	CONSTRAINT FK_ModoPagamento
		FOREIGN KEY (IdModoPagamento)
		REFERENCES ModoPagamento(Id)
)

CREATE TABLE Carro
(
	Id				INT IDENTITY NOT NULL,
	IdMarca			INT NOT NULL,
	IdModelo		INT NOT NULL,
	IdAno			INT NOT NULL,
	IdCor			INT NOT NULL,
	IdFinanceiro	INT, /*NULL SE CARRO ESTIVE INDISPONIVEL PARA VENDA*/
	CONSTRAINT PK_Carro PRIMARY KEY(Id),
	CONSTRAINT FK_Marca
		FOREIGN KEY (IdMarca)
		REFERENCES Marca(Id),
	CONSTRAINT FK_Modelo
		FOREIGN KEY (IdModelo)
		REFERENCES Modelo(Id),
	CONSTRAINT FK_Ano
		FOREIGN KEY (IdAno)
		REFERENCES Ano(Id),
	CONSTRAINT FK_Cor
		FOREIGN KEY (IdCor)
		REFERENCES Cor(Id),
	CONSTRAINT FK_Financeiro
		FOREIGN KEY (IdFinanceiro)
		REFERENCES Financeiro(Id)
)

CREATE TABLE Favorito
(
	Id			INT IDENTITY NOT NULL,
	IdCliente	INT NOT NULL,
	IdCarro		INT NOT NULL,
	CONSTRAINT PK_Favorito PRIMARY KEY(Id),
	CONSTRAINT FK_Cliente
		FOREIGN KEY (IdCliente)
		REFERENCES Cliente(Id),
	CONSTRAINT FK_CarroFavorito
		FOREIGN KEY (IdCarro)
		REFERENCES Carro(Id),
)

CREATE TABLE Opcional
(
	Id			INT IDENTITY NOT NULL,
	Nome	VARCHAR(10) NOT NULL,
	CONSTRAINT PK_Opcional PRIMARY KEY(Id)
)

CREATE TABLE OpcionalNoCarro
(
	Id			INT IDENTITY NOT NULL,
	IdOpcional	INT NOT NULL,
	IdCarro		INT NOT NULL,
	CONSTRAINT PK_OpcionalNoCarro PRIMARY KEY(Id),
	CONSTRAINT FK_Opcional
		FOREIGN KEY (IdOpcional)
		REFERENCES Opcional(Id),
	CONSTRAINT FK_CarroOpcional
		FOREIGN KEY (IdCarro)
		REFERENCES Carro(Id)
)